export const CHANGE_USER = "CHANGE_USER";
export const POST_NEW_ORDER = "POST_NEW_ORDER";
export const TRADES_LOADED = "TRADES_LOADED";
export const MY_ORDERS_LOADED = "MY_ORDERS_LOADED";
export const PENDING_ORDERS_LOADED = "PENDING_ORDERS_LOADED";
export const MARKET_DEPTH_LOADED = "MARKET_DEPTH_LOADED";

