export const CHANGE_USER = "CHANGE_USER";
export const GET_TRADES = "GET_TRADES";
export const GET_MY_ORDERS = "GET_MY_ORDERS";
export const GET_PENDING_ORDERS = "GET_PENDING_ORDERS";
export const POST_NEW_ORDER = "POST_NEW_ORDER";
export const TRADES_LOADED = "TRADES_LOADED";
export const MY_ORDERS_LOADED = "MY_ORDERS_LOADED";
export const PENDING_ORDERS_LOADED = "PENDING_ORDERS_LOADED";

